### ISSUE TITLE
Would like to implement auto sorting in the plugin

### ISSUE THREAD

**Issue by PhilippeMarcMeyer** [PhilippeMarcMeyer/FieldsLinker#1]
Autosorting would allow the user to always se the lines drawn horizontaly which is much easier than a bunch of lines all crossed.
while exchanging the LI in the right UL, I mess with the offset 
If this interest someone i'd be pleased to explain further and cooperate

**Comment by devendarpilli** [comment]
I would like to see how this works. Can you please explain. 
I want to place the items with no link to the destination at the bottom of the list.

Thanks.
