### ISSUE TITLE
Issue with Content Length

### ISSUE THREAD

**Issue by ankitravan** [PhilippeMarcMeyer/FieldsLinker#14]
Hi PhilippeMarcMeyer,

I am using FieldsLinker and it is a great field linker.

But i have one issue with '<td>' tags. if my value is to long that time i am not able to view this value inside the td tag.

It getting hide. 

If you resolve this then it will be good to me and fieldsLinker. 

Again thanks for build this plugin.

" I have one Idea may be it will work. If you can give a separate scroll bar to left and right div : ( $leftDiv = $('<div></div>')). "

![Capture](https://user-images.githubusercontent.com/53144540/72593283-9cc83e80-392a-11ea-846d-6af6ba1bf855.PNG)

**Comment by PhilippeMarcMeyer** [comment]
Hi ankitravan !
Well I didn't design FieldLinker with long column names in mind in the first place !
This plugin is evolving with pairs developpers demands like yours :-)
First of all :
There are a few ideas you could use without modifying anything or very little as it does not like very convenient to display very long names

1- Make an array of matching with shorter names [{"original":"very long name ...","short":"name"},...]
display the short names and math the resulting links at the end (your job)

2- return to line => wrap words (with little changes in the plug-in) We could declare as an option that we should go to the next line between "]" and "["
let options = {"wrapBegin":"]","wrapEnd":"[",...}

What is your opinon ?

**Comment by PhilippeMarcMeyer** [comment]
No answer yet ?
well I did v 0.92 for you 
just add an option  "whiteSpace":"normal"
