### ISSUE TITLE
How to Create Multiple FieldsLinker in Same Page

### ISSUE THREAD

**Issue by pranaysonisoft** [PhilippeMarcMeyer/FieldsLinker#15]
I need a two instance in same page 
but when i create second FieldsLinker   First  FieldsLinker right side is Removed.

**Comment by PhilippeMarcMeyer** [comment]
Yes I knew I'll have to rewrite it some day.  I'll do it as soon as possible.

**Comment by PhilippeMarcMeyer** [comment]
I've got to rewrite it to allow multiple instances

**Comment by PhilippeMarcMeyer** [comment]
It took me a while but here it is a multiple instances vers (v0.95)
