### ISSUE TITLE
How to add list filters

### ISSUE THREAD

**Issue by rsmithtorres** [PhilippeMarcMeyer/FieldsLinker#17]
Hello Philippe.

Thanks for your plugin... it works great.

I have a question... I tried to use filters using:

"Lists":[{
	"filter":true,
	"keysFilter": ["libelle"]
}]

But I the page shows only two ddl with "Columns in fields" and "Avalilable fields" options.

I don't know if aditional configuration is needed.... and what should be the "keysFilter" value.

Any help will be appreciated.

Thanks in advance and best regards.

Roberto Smith

**Comment by PhilippeMarcMeyer** [comment]
Hello Roberto,

For the present time the option is broken
I'm goint to redo it muche simpler and provide examples as soon as possible

Thank you for letting me know about this bug

Philippe Meyer

**Comment by rsmithtorres** [comment]
Hello Philippe.

Thanks for your answer... I'm glad it wasn't me who did something wrong ;)

Thanks again for this plugin!

Roberto Smith
