### ISSUE TITLE
input some links from a previous session

### ISSUE THREAD

**Issue by MohamedAhmed12** [PhilippeMarcMeyer/FieldsLinker#20]
Hello,
May I know how to input some links from a previous session ? to create the 2 group with predefined matching (pre-connected) ? 

Thanks

**Comment by PhilippeMarcMeyer** [comment]
Hello Mohamed,
just add a property to the input object :
"existingLinks": [{ "from": "lastName", "to": "last_name" }, { "from": "firstName", "to": "first_name" }, { "from": "role", "to": "jobTitle" }]
so you can store links between session, to automaticaly check files and see you kwon this pattern and import them directly in your database.
I'm going to add this to the readme page

Thank you

Philippe
