### ISSUE TITLE
Get list from Database

### ISSUE THREAD

**Issue by devendarpilli** [PhilippeMarcMeyer/FieldsLinker#21]
How to populate the list with the values got from the database? I could not find any help. Please help.

**Comment by PhilippeMarcMeyer** [comment]
It's your job to establish this list. 
For instance, you want your partner to be able to upload files containing new products for you to sell
you will select label, price,quantity_available,tax % etc...
Once you've got it, set the ListB :
```
				"listB":
					{
						"name":"Fields available",
						"list" : [
							"Id",
							"Company",
							"jobTitle",
							"adress 1",	
							"adress 2",	
							"first_name",
							"last_name",
							"email_adress",
							"Phone number"
						]
					}
```
