### ISSUE TITLE
Is there any option to Unlink the links with Mobile Click It set to true?

### ISSUE THREAD

**Issue by devendarpilli** [PhilippeMarcMeyer/FieldsLinker#22]

**Comment by PhilippeMarcMeyer** [comment]
Hello devendarpilli,

Yes there is one : double click on the destination item 
I realise that maybe it is not very convenient on a mobile device
maybe a litterbin icon would be better ?
Please let me know
Sincerely

Philip

**Comment by devendarpilli** [comment]
The double click is working on desktop.

Thanks.
