### ISSUE TITLE
Jquery 3.5.0 compatibility 

### ISSUE THREAD

**Issue by MohamedAhmed12** [PhilippeMarcMeyer/FieldsLinker#23]
Hello, 
So I have to use JQuery 3.5.0 and I'm working with Nuxt, I've noticed that you used version 2, I have these errors and correct me if I'm wrong are they Jquery version compatibility errors ? and If they are what should I do to fix this.

![image](https://user-images.githubusercontent.com/30234716/83164880-0d6b3d00-a10d-11ea-8364-be914fb4547a.png)

![image](https://user-images.githubusercontent.com/30234716/83164986-325fb000-a10d-11ea-89aa-5c19ffa958e8.png)

**Comment by PhilippeMarcMeyer** [comment]
Working on it :
jquery does not return the parebt div width and height of the canvas
ex : var w = self.$midDiv.width(); w is 0 !

**Comment by PhilippeMarcMeyer** [comment]
FieldsLinker is not compatible with jquery 3.5

I made it with jquery 2.2
