### ISSUE TITLE
incompatibility with jquery 3

### ISSUE THREAD

**Issue by Deler-T-Abdolqader** [PhilippeMarcMeyer/FieldsLinker#24]
I really liked FieldsLinker, I was happy to be able to use it in my project, but unfortunately after using it I realized that it has a problem with Jquery version 3. I hope you can fix it. Thank you

**Comment by PhilippeMarcMeyer** [comment]
Hi Deler ! thank for this issue : the plugin is now compatible jquery 3.5 :-)
