### ISSUE TITLE
[Enhancement] Add list of labels

### ISSUE THREAD

**Issue by adrienmaloba** [PhilippeMarcMeyer/FieldsLinker#29]
I suggest to add a third list that will allow to add labels to the fields of the list "listB". These labels will be displayed instead of the fields in the "listB" list. 
This will allow users to customize their display when the elements of the listB list are dynamic, if they are the fields of a SQL table for example. 
Currently instead of "client_name", the user will see "Client Name" or any other label.

**Comment by PhilippeMarcMeyer** [comment]
hello Adrien,

Yes we could do that

I was just pondering if it was very useful as you may do your own
translation : you dont have to give directly the sql field name. the entry
could has well correspond to something in another table : for instance the
name of the company and the name of an employee eas go in separated tables.
i understand it would be convenient and will try to find some time to do it
as it it a 'nice to have'

thank you for this idea

philip
