### ISSUE TITLE
Filedslinker is not working in touch devices

### ISSUE THREAD

**Issue by chinna-magapu** [PhilippeMarcMeyer/FieldsLinker#3]
Hi, I am using  FieldsLinker plugin in my project and it is a great plugin to link or map fields between two lists. But I am facing the issue when I am trying to link fields in Touch devices it is not working.

I tried to map the mouse events such as ( Mouse Up / Mouse Down ) with Touch events. but didn't work. Please provide any update on this functionality if possible. that will help a lot to all users.

Thanks in Advance.

**Comment by PhilippeMarcMeyer** [comment]
I'm glad you like it :-) I didn't designed it for touch devices in the first place and i'm going to think about the best way to do it :-)

**Comment by PhilippeMarcMeyer** [comment]
I have made a first relase (v0.85) which works on my tablet.
sometimes it doesn't work and I have to trace the link twice to make it work
I didn't implement drag and drop sorting on mobile yet.
Please try it if you want and give me feed back

**Comment by chinna-magapu** [comment]
Thanks a lot, Now I am trying to implement the latest version and update my feedback. 
Thank You Again.
