### ISSUE TITLE
Reordering the elements the list rehabilitates itself

### ISSUE THREAD

**Issue by attyskater** [PhilippeMarcMeyer/FieldsLinker#30]
Hi,

As per the title, just go [here](https://philippemarcmeyer.github.io/FieldsLinker/index.html?v=1.02), Click Disable and drag the items in the list to reorder them. 
An option to disable reordering as well would be very useful.

thanks

**Comment by PhilippeMarcMeyer** [comment]
Thank you for this bug detection : it's fixed in new version 1.03 (sorry for the delay)
