### ISSUE TITLE
Use tag versions

### ISSUE THREAD

**Issue by xorti** [PhilippeMarcMeyer/FieldsLinker#31]
Hello,

Is it possible to add release tags to the repository?
That would allow for users to select which version to use in composer, and not rely on the latest commit in master.

Thanks and keep up the good work!

**Comment by PhilippeMarcMeyer** [comment]
Hi! Could you give me an example ? Is it a JSON file ? What should it contains ?
Thank you and happy new year (as I was a little long to answer your 2011 question!)

**Comment by PhilippeMarcMeyer** [comment]
I will make a package.json file soon. Hope it's what you want (like id did for vanillaSelectBox)

**Comment by xorti** [comment]
Hi @PhilippeMarcMeyer the JSON file is already present and OK - https://github.com/PhilippeMarcMeyer/FieldsLinker/blob/master/composer.json

This repository only needs some tags: https://github.com/PhilippeMarcMeyer/FieldsLinker/tags

After that, the tags will be available in https://packagist.org/packages/philippemarcmeyer/fieldslinker

Thanks

**Comment by PhilippeMarcMeyer** [comment]
Done 🙂
