### ISSUE TITLE
Could Lists.list support jquery/javascript object?

### ISSUE THREAD

**Issue by JerryX** [PhilippeMarcMeyer/FieldsLinker#4]
Good plugin! And could you add the support to next upgrade?

**Comment by PhilippeMarcMeyer** [comment]
Thank you ! 
Sorry I don't get what you mean ?

**Comment by JerryX** [comment]
Sorry!Forgive my terrible English!
What I mean is
`
var $left0 = $('#left0');
var $left1 = $('#left1');
var $right0 = $('#right0');
var $right1 = $('#right1');
"listA":
 {
						"name":"columns in files",
						"list" : [
							$left0,
                                                        $left1
						]
					},
				"listB":
					{
						"name":"Fields available",
						"list" : [
							$right0,
                                                        $right1
						]
}
`
could fill javascript/jQuery object into 'list' attr

**Comment by PhilippeMarcMeyer** [comment]
The goal of the plugin is to match a text file header with DB fields 
The links drawn can but later used to automaticaly recognize the file and thus speed up the process.
I think it's the developper responsability to fill the columns by providing the arrays to the plugin.
So I'm sorry but I don't think it's a good idea.
Future improvements could be : 
- adding a number to header items if the left array contains duplicates
- giving back the sorting when you re-load known links into the plugin
- automatic sorting of the links as an option
- better support of mobile

If you have any idea : it is welcome
If you need help to use the plugin send me a mail

**Comment by PhilippeMarcMeyer** [comment]
Ok Jerry, I close this issue then
